name: fading_text_animation
description: A Flutter app with fading text, cute animal images, and animations.

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For picking text colors
  flutter_colorpicker: ^1.0.3

  # Cupertino icons for iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # If later you want to use local images, uncomment and add them
  # assets:
  #   - assets/images/panda.png
  #   - assets/images/puppy.png
